apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-paths

spec:
  rules:
  - host: 
    http:
      paths:
      - path: "/"
        backend:
          serviceName: nginx
          servicePort: 80

      #- path: "/"
      #  backend:
      #    serviceName: apache
      #    servicePort: 8080
