---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eks-alb-testing-deployment"
spec:
  selector:
    matchLabels:
      app: "eks-alb-testing-web"
  replicas: 1
  template:
    metadata:
      labels:
        app: "eks-alb-testing-web"
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: "eks-alb-testing-web-nginx"
        ports:
        - containerPort: 80  
          
---
apiVersion: v1
kind: Service
metadata:
  name: "eks-alb-testing-web-service"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:          
    app: "eks-alb-testing-web"
    
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "eks-alb-testing-web-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: bttrm-eks-dev-0-web
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "eks-alb-testing-web-service"
              servicePort: 80
